### ISSUE TITLE
what's about some tools to generate simplestreams json

### ISSUE THREAD

**Issue by erickeller** [smoser/talk-simplestreams#3]
Hi there,

I bumped into your talk and notes about the simplestreams usage and applications.
Interesting, probably the best intro so far.
I am wondering what's the best way to generate simplestreams? I am currently investigating on generating simplestreams for our internal LXD registery.
It's not really easy to jump into the launchpad source for simplestreams. I would be glad to get some hints here, since there is also not much documented about the json key values...

Eric

**Comment by smoser** [comment]
The best tools that currently exist for generating streams are in the simplstreams repo.

See `./tools/tab2streams` and `./bin/json2streams`.

Sorry, there isn't much more than that at the moment.
